TwoHoSun.xcodeproj/project.pbxproj
TwoHoSun/.swiftlint.yml
TwoHoSun/Screens/Login/LoginModel.swift
TwoHoSun/Screens/Login/LoginView.swift
TwoHoSun/Screens/Login/LoginViewModel.swift
TwoHoSun/TwoHoSunApp.swift

🍃 작업한 브랜치
- feat/ #1 
애플로그인을 통해 Authorizationcode를 Alamofire를 이용하여 서버에서 AccessToken과 RefreshToken을 받는다. 
data.data.accessToken = AccessToken 서버로부터 받는 데이터의 모델은 LoginModel이라고 만들어 놓았음. 
- Resolved: #1

애플로그인 토큰 요청

---

TwoHoSun.xcodeproj/project.pbxproj
TwoHoSun/Screens/ProfileSettings/View/ProfileSettingsView.swift

🍃 작업한 브랜치
- feature/#2
- 프로필 레이아웃 그리기
- 학년 드롭다운 추가
- 프로필 사진 기능 추가
- Resolved: #2

프로필설정뷰 레이아웃 그리기 및 기능 추가

---

.gitignore
TwoHoSun.xcodeproj/project.pbxproj
TwoHoSun/Resources/Secret.plist
TwoHoSun/Screens/ProfileSettings/SchoolSearchViewModel.swift

🍃 작업한 브랜치
- feature/#20
plist에 api key 저장 및 불러오기
- Resolved: #20

학교 정보 API Key 저장

---

TwoHoSun.xcodeproj/project.pbxproj
TwoHoSun/Model/GeneralResponse.swift
TwoHoSun/Model/LoginModel.swift
TwoHoSun/Screens/Home/HomeView.swift
TwoHoSun/Screens/OnBoarding/BottomSheetView.swift
TwoHoSun/Screens/OnBoarding/LoginViewModel.swift
TwoHoSun/Screens/OnBoarding/OnBoardingView.swift
TwoHoSun/Screens/ProfileSettings/ProfileSettingsView.swift
TwoHoSun/TwoHoSunApp.swift

🍃 작업한 브랜치
- feature/ #15 
- 409와 메시지를 받으면 동의하기 하프모달이 뜨도록 함.
- 아니라면 바로 메인뷰로 넘어가도록 구현
- Notion에 있는 GeneralResponse 모델 생성.
- BottomSheetView에서 텍스트를 클릭해도 체크박스가 바뀌도록 설정
- 콤바인을 이용하여 서버와 통신
- navigationStack 생성
- Resolved: #15 
현재 로그인이 너무 느립니다. 뭐가 문제인지 잘 모르겠어서 일단 코드를 리팩할때 더 살펴볼 예정입니다.

로그인할때 회원정보 있는지 체크

---

TwoHoSun.xcodeproj/project.pbxproj
TwoHoSun/Screens/Home/Vote/ImageDetailView.swift
TwoHoSun/Screens/Home/Vote/LinkView.swift
TwoHoSun/Screens/Home/Vote/VoteContentView.swift

🍃 작업한 브랜치
- feature/#38
- 링크 버튼 눌렀을 때 해당 웹뷰 띄우기
- Resolved: #38

링크 버튼 눌렀을 때 해당 링크 웹뷰 띄우기

---

TwoHoSun/Network/APIManager.swift
TwoHoSun/Screens/OnBoarding/LoginViewModel.swift
TwoHoSun/Screens/ProfileSettings/ProfileSettingViewModel.swift
TwoHoSun/TwoHoSunApp.swift

🍃 작업한 브랜치
- feature/#48
APIManager 헤더 수정 및 파라미터 추가
- Resolved: #48

APIManager 헤더 수정 및 파라미터 추가

---

TwoHoSun.xcodeproj/project.pbxproj
TwoHoSun/Model/DTO/VoteCreateRequestModel.swift
TwoHoSun/Network/APIManager.swift
TwoHoSun/Resources/Secret.plist
TwoHoSun/Screens/Home/Vote/VoteContentView.swift
TwoHoSun/Screens/Home/Vote/VoteContentViewModel.swift
TwoHoSun/TwoHoSunApp.swift

🍃 작업한 브랜치
- feature/#45
게시글 투표 api 통신
- Resolved: #45

게시글 투표 api 통신

---

TwoHoSun/Model/DTO/SchoolResponseModel.swift
TwoHoSun/Resources/Secret.plist
TwoHoSun/Screens/Home/MainView/SearchView.swift
TwoHoSun/TwoHoSunApp.swift

🍃 작업한 브랜치
- feature/#55
- 프로필세팅뷰 지역 데이터 두 글자 포맷으로 변경 (ex. 서울특별시 -> 서울)
- Resolved: #55

프로필세팅뷰 지역 데이터 형식 변경

---

TwoHoSun/Screens/Home/MainView/NotificationView.swift
TwoHoSun/Screens/Home/MainView/SeachViewModel.swift
TwoHoSun/Screens/Home/MainView/SearchView.swift

🍃 작업한 브랜치
- feature/#70
통합 검색 뷰에 대한 버그 수정
- Resolved: #70

검색 뷰 버그 수정

---

TwoHoSun/Model/DTO/PostResponseModel.swift
TwoHoSun/Model/DTO/VoteCreateRequestModel.swift
TwoHoSun/Model/FeedModel/PostModel.swift
TwoHoSun/Model/PostCreateModel.swift
TwoHoSun/Network/APIManager.swift
TwoHoSun/Screens/Home/DetailView/DetailView.swift
TwoHoSun/Screens/Home/DetailView/DetailViewModel.swift
TwoHoSun/Screens/Home/Vote/VoteContentView.swift
TwoHoSun/Screens/Home/Write/WriteViewModel.swift

🍃 작업한 브랜치
- feature/#67
게시글 상세 조회 api 통신
- Resolved: #67

게시글 상세 조회 api 통신

---

TwoHoSun/Screens/Home/DetailView/CommentCell.swift
TwoHoSun/Screens/Home/DetailView/DetailView.swift
TwoHoSun/Screens/Home/DetailView/DetailViewModel.swift
TwoHoSun/Screens/Home/Vote/VoteContentView.swift

🍃 작업한 브랜치
- feature/ #78 
수정된 댓글 UI & 댓글 이어달기 & 대댓글 작업
- Resolved:  #78

feat(comments): modify UI and add nested reply

---

TwoHoSun.xcodeproj/project.pbxproj
TwoHoSun/AppDelegate.swift
TwoHoSun/TwoHoSunApp.swift

🍃 작업한 브랜치
- feat/#81
- push notification 을 위한 기본적인 세팅을 진행했습니다.
- swiftui 에서 AppDelegate 사용을 위한 코드를 추가했습니다.
풀스택 왔다 감.
- Resolved: #81

Push notification를 위한 AppDelegate 추가

---

.gitignore
TwoHoSun.xcodeproj/project.pbxproj
TwoHoSun/Info.plist
TwoHoSun/Resources/Secret.plist
TwoHoSun/Resources/Secret.xcconfig
TwoHoSun/Screens/ProfileSettings/SchoolSearchView.swift
TwoHoSun/Screens/ProfileSettings/SchoolSearchViewModel.swift
TwoHoSun/TwoHoSunApp.swift

🍃 작업한 브랜치
- feature/#121
- config 파일 생성
- @Observable -> ObservableObject로 변경
- Resolved: #

Secret key 파일 오류 해결

---

TwoHoSun.xcodeproj/project.pbxproj
TwoHoSun/Model/DTO/VoteCreateRequestModel.swift
TwoHoSun/Model/FeedModel/PostModel.swift
TwoHoSun/Model/LoginModel/Tokens.swift
TwoHoSun/Model/PostCreateModel.swift
TwoHoSun/Network/Service/PostService.swift
TwoHoSun/Network/Service/UserService.swift
TwoHoSun/Screens/Common/NoReviewView.swift
TwoHoSun/Screens/Common/NoVoteView.swift
TwoHoSun/Screens/Common/WoteTabView.swift
TwoHoSun/Screens/Home/Detail/DetailViewModel.swift
TwoHoSun/Screens/Home/Main/ConsiderationView.swift
TwoHoSun/Screens/Home/VoteWrite/VoteWriteView.swift
TwoHoSun/Screens/Home/VoteWrite/VoteWriteViewModel.swift

🍃 작업한 브랜치
- feature/#130
투표만들기 API 연결
- Resolved: #130

투표만들기 API 연결

---

TwoHoSun/Extensions/View+.swift
TwoHoSun/Network/Manager/NewApiManager.swift
TwoHoSun/Network/Service/PostService.swift
TwoHoSun/Screens/Component/CustomAlertModalView.swift
TwoHoSun/Screens/Component/CustomConfirmModifier.swift
TwoHoSun/Screens/Home/Detail/CommentsView.swift
TwoHoSun/Screens/Home/Detail/DetailView.swift
TwoHoSun/Screens/Home/Detail/DetailViewModel.swift
TwoHoSun/Screens/Home/Main/VoteViewModel.swift
TwoHoSun/Screens/Home/VoteWrite/VoteWriteView.swift
TwoHoSun/Screens/ProfileSettings/ProfileSettingsView.swift
TwoHoSun/Screens/Review/ReviewWrite/Review/ReviewWrite/ReviewWriteView.swift
TwoHoSun/Utility/NavigationManager.swift

🍃 작업한 브랜치
- feature/#147
action sheet UI 수정
투표 삭제 / 투표 즉시 종료 API
- Resolved: #147

투표 삭제 / 투표 즉시 종료 API 연결

---

TwoHoSun/AppDelegate.swift
TwoHoSun/Info.plist

🍃 작업한 브랜치
- feature/#135
#135  여기서 사용법을 참고하세요
- Resolved: #135

Notification 기초 공사

---

TwoHoSun.xcodeproj/project.pbxproj
TwoHoSun/Model/ReviewCreateModel.swift
TwoHoSun/Network/Service/PostService.swift
TwoHoSun/Screens/Common/NoReviewView.swift
TwoHoSun/Screens/Component/ImageCropView.swift
TwoHoSun/Screens/Component/VoteCardCell.swift
TwoHoSun/Screens/Home/Detail/DetailHeaderView.swift
TwoHoSun/Screens/Home/VoteWrite/VoteWriteView.swift
TwoHoSun/Screens/MyPage/MyPageView.swift
TwoHoSun/Screens/Review/ReviewWrite/Review/ReviewWrite/ReviewWriteView.swift
TwoHoSun/Screens/Review/ReviewWrite/Review/ReviewWrite/ReviewWriteViewModel.swift

🍃 작업한 브랜치
- feature/#155
후기 작성하기 API 연결
리뷰 작성 뷰가 필요한 뷰들에 대한 각자 작업 완료 후 연결해야합니다.
- Resolved: #155

후기 작성하기 API 연결

---

TwoHoSun.xcodeproj/project.pbxproj
TwoHoSun/Network/Service/UserService.swift
TwoHoSun/Screens/Common/WoteTabView.swift
TwoHoSun/Screens/MyPage/MyPageView.swift
TwoHoSun/Screens/MyPage/Setting/SettingTermsView.swift
TwoHoSun/Screens/MyPage/Setting/SettingView.swift
TwoHoSun/Screens/MyPage/Setting/SettingViewModel.swift
TwoHoSun/Screens/OnBoarding/OnBoardingView.swift

🍃 작업한 브랜치
- feature/#161
회원 탈퇴 API 연결 및 로그아웃 구현
- Resolved: #161

회원 탈퇴 API 연결 및 로그아웃 구현

---

TwoHoSun/Screens/Common/NoReviewView.swift
TwoHoSun/Screens/Common/NoVoteView.swift
TwoHoSun/Screens/Home/Main/VoteContentCell.swift

🍃 작업한 브랜치
- feature/#195
- 고민 등록하러가기에서도 소비 성향 테스트 뜨도록
- 투표 시에 소비 성향 테스트 오류 해결
- Resolved: #

소비 성향 테스트하지 않았을 때 처리

---

TwoHoSun.xcodeproj/project.pbxproj
TwoHoSun/Screens/Home/Main/ConsiderationView.swift
TwoHoSun/Screens/OnBoarding/BottomSheetView.swift
TwoHoSun/Utility/TermAgreeType.swift

🍃 작업한 브랜치
- feature/#197
- Resolved: #197

심사 후 버그 fix
